/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20Permit__factory } from "./ERC20Permit__factory";
export { IERC20Permit__factory } from "./IERC20Permit__factory";
