/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface MockObservationsInterface extends utils.Interface {
  functions: {
    "liquidity()": FunctionFragment;
    "observations(uint256)": FunctionFragment;
    "slot0()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "liquidity" | "observations" | "slot0"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "liquidity", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "observations",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "slot0", values?: undefined): string;

  decodeFunctionResult(functionFragment: "liquidity", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "observations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "slot0", data: BytesLike): Result;

  events: {};
}

export interface MockObservations extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MockObservationsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    liquidity(overrides?: CallOverrides): Promise<[BigNumber]>;

    observations(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number, BigNumber, BigNumber, boolean]>;

    slot0(
      overrides?: CallOverrides
    ): Promise<[BigNumber, number, number, number, number, number, boolean]>;
  };

  liquidity(overrides?: CallOverrides): Promise<BigNumber>;

  observations(
    index: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[number, BigNumber, BigNumber, boolean]>;

  slot0(
    overrides?: CallOverrides
  ): Promise<[BigNumber, number, number, number, number, number, boolean]>;

  callStatic: {
    liquidity(overrides?: CallOverrides): Promise<BigNumber>;

    observations(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number, BigNumber, BigNumber, boolean]>;

    slot0(
      overrides?: CallOverrides
    ): Promise<[BigNumber, number, number, number, number, number, boolean]>;
  };

  filters: {};

  estimateGas: {
    liquidity(overrides?: CallOverrides): Promise<BigNumber>;

    observations(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    slot0(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    liquidity(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    observations(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    slot0(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
